quarkus.application.name=countriesApp
quarkus.http.port=8080

# external api - client
quarkus.rest-client.countries-api.url=https://api.restcountries.com
countries-api.key=rc_live_a7f32d9a88e84e3f8912e4f412d650fe

# mongoDB
quarkus.mongodb.connection-string=${QUARKUS_MONGO_URI:mongodb://localhost:27017}
quarkus.mongodb.database=countriesDB

# Redis
quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

# kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.outgoing.visit-tracker-out.connector=smallrye-kafka
mp.messaging.outgoing.visit-tracker-out.topic=visit-tracker
mp.messaging.outgoing.visit-tracker-out.value.serializer=com.example.serializers.CountrySerializer

mp.messaging.incoming.visit-tracker-in.connector=smallrye-kafka
mp.messaging.incoming.visit-tracker-in.topic=visit-tracker
mp.messaging.incoming.visit-tracker-in.value.deserializer=com.example.deserializers.CountryDeserializer

mp.messaging.outgoing.visited.connector=smallrye-kafka
mp.messaging.outgoing.visited.topic=visited
mp.messaging.outgoing.visited.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.not-visited.connector=smallrye-kafka
mp.messaging.outgoing.not-visited.topic=not-visited
mp.messaging.outgoing.not-visited.value.serializer=org.apache.kafka.common.serialization.StringSerializer
