apiVersion: v1
kind: Service
metadata:
  name: quarkus-countries-app-svc
spec:
  type: NodePort
  selector:
    app: quarkus-countries-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080